# Generated by Django 3.0.8 on 2020-07-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('idCeremony', models.IntegerField(primary_key=True, serialize=False)),
                ('nameOfCeremony', models.CharField(max_length=50)),
                ('duration', models.FloatField(max_length=4)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('idDuty', models.IntegerField(primary_key=True, serialize=False)),
                ('typeOfDuy', models.CharField(choices=[('Kmp', 'Kompania'), ('Sto', 'Stołówka'), ('Str', 'Strzelnica'), ('Pst', 'PST')], max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.IntegerField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PersonOnDuty',
            fields=[
                ('idRegistration', models.IntegerField(primary_key=True, serialize=False)),
                ('idDuty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Duty')),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonOnCeremony',
            fields=[
                ('idRegistration', models.IntegerField(primary_key=True, serialize=False)),
                ('idCeremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Ceremony')),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Person')),
            ],
        ),
    ]
