# Generated by Django 3.0.8 on 2020-08-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('idCeremony', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfCeremony', models.CharField(max_length=50)),
                ('duration', models.FloatField(max_length=4)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('idDuty', models.AutoField(primary_key=True, serialize=False)),
                ('typeOfDuty', models.CharField(choices=[('Kmp', 'Kompania'), ('Sto', 'Stołówka'), ('Str', 'Strzelnica'), ('Pst', 'PST'), ('Bat', 'Batalionowa')], max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('numberOfDuty', models.FloatField(default=0)),
                ('numberOfCeremony', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('idSoldier', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PersonOnDuty',
            fields=[
                ('idRegistration', models.AutoField(primary_key=True, serialize=False)),
                ('idDuty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Duty')),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonOnCeremony',
            fields=[
                ('idRegistration', models.AutoField(primary_key=True, serialize=False)),
                ('idCeremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Ceremony')),
                ('idPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppSluzby.Person')),
            ],
        ),
    ]
