# Generated by Django 3.0.8 on 2020-09-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSluzby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='typeOfDuty',
            field=models.CharField(choices=[('Kmp', 'Kompania'), ('Sto', 'Stołówka'), ('Str', 'Strzelnica'), ('Pst', 'PST'), ('Bat', 'Batalionowa'), ('War', 'Wartownicza')], max_length=3),
        ),
    ]
