# Generated by Django 3.0.8 on 2020-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSluzby', '0002_auto_20200729_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='numberOfCeremony',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='numberOfDuty',
            field=models.FloatField(default=0),
        ),
    ]
