# Generated by Django 3.0.8 on 2020-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSluzby', '0003_auto_20200731_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='typeOfDuty',
            field=models.CharField(choices=[('Kmp', 'Kompania'), ('Sto', 'Stołówka'), ('Str', 'Strzelnica'), ('Pst', 'PST'), ('Bat', 'Batalionowa')], max_length=3),
        ),
    ]
