# Generated by Django 3.0.8 on 2020-07-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSluzby', '0004_auto_20200731_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='degree',
        ),
    ]
