# Generated by Django 3.0.8 on 2020-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSluzby', '0005_remove_person_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremony',
            name='idCeremony',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='duty',
            name='idDuty',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='idPerson',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persononceremony',
            name='idRegistration',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persononduty',
            name='idRegistration',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
